const fs=require('fs');const p=require('path');
const W=[
{w:"teach",i:"/tiːtʃ/",p:"TEECH",pos:"verb",lv:"A1",me:"To give lessons or instructions to someone",mv:"Dạy, giảng dạy",ee:"She teaches English at a primary school.",ev:"Cô ấy dạy tiếng Anh ở trường tiểu học.",c:"teach a lesson|teach someone how|teach school",s:"instruct|educate|train",a:"learn|study",t:"education|daily-life|work-business"},
{w:"tear",i:"/tɛr/",p:"TAIR",pos:"verb,noun",lv:"A2",me:"To pull something apart by force; a drop of liquid from the eye",mv:"Xé, rách; nước mắt",ee:"Be careful not to tear the paper.",ev:"Cẩn thận đừng xé rách giấy.",c:"tear apart|tear up|tear drop|in tears",s:"rip|shred|cry|weep",a:"mend|repair",t:"daily-life|emotion-personality"},
{w:"teeth",i:"/tiːθ/",p:"TEETH",pos:"noun",lv:"A1",me:"The hard white structures in the mouth used for biting",mv:"Răng (số nhiều)",ee:"Brush your teeth twice a day.",ev:"Đánh răng hai lần mỗi ngày.",c:"brush teeth|baby teeth|teeth whitening",s:"dental|molars",a:"",t:"health|daily-life"},
{w:"thick",i:"/θɪk/",p:"THIK",pos:"adjective",lv:"A2",me:"Having a large distance between opposite sides; not thin",mv:"Dày, dày đặc",ee:"The book has thick pages.",ev:"Cuốn sách có những trang dày.",c:"thick and thin|thick layer|thick fog",s:"dense|broad|heavy",a:"thin|slim|narrow",t:"daily-life|environment-nature"},
{w:"thin",i:"/θɪn/",p:"THIN",pos:"adjective",lv:"A2",me:"Having a small distance between opposite sides; not thick",mv:"Mỏng, gầy",ee:"She wore a thin jacket in the cold.",ev:"Cô ấy mặc áo khoác mỏng trong trời lạnh.",c:"thin layer|thin air|paper thin",s:"slim|slender|narrow",a:"thick|fat|wide",t:"daily-life|clothing-fashion|health"},
{w:"throw",i:"/θroʊ/",p:"THROH",pos:"verb,noun",lv:"A2",me:"To send something through the air by moving the arm",mv:"Ném, quăng",ee:"Throw the ball to me.",ev:"Ném bóng cho tôi.",c:"throw away|throw up|throw a party",s:"toss|hurl|fling",a:"catch|hold",t:"daily-life|sports-fitness"},
{w:"tie",i:"/taɪ/",p:"TYE",pos:"verb,noun",lv:"A2",me:"To fasten with a knot; a piece of cloth worn around the neck",mv:"Buộc, thắt; cà vạt",ee:"He learned to tie his shoes at age five.",ev:"Anh ấy học buộc dây giày lúc năm tuổi.",c:"tie a knot|neck tie|tie up|bow tie",s:"fasten|bind|knot|necktie",a:"untie|loosen",t:"daily-life|clothing-fashion"},
{w:"tired",i:"/taɪərd/",p:"TY-erd",pos:"adjective",lv:"A1",me:"Feeling that you need to rest or sleep",mv:"Mệt mỏi",ee:"I am tired after a long day at work.",ev:"Tôi mệt mỏi sau một ngày dài làm việc.",c:"feel tired|tired of|tired out",s:"exhausted|weary|fatigued",a:"energetic|refreshed|rested",t:"daily-life|health|emotion-personality"},
{w:"toe",i:"/toʊ/",p:"TOH",pos:"noun",lv:"A2",me:"One of the five small parts at the end of the foot",mv:"Ngón chân",ee:"She hurt her toe on the table leg.",ev:"Cô ấy đau ngón chân vì va vào chân bàn.",c:"big toe|from head to toe|toe nail",s:"digit",a:"finger",t:"health|daily-life"},
{w:"tongue",i:"/tʌŋ/",p:"TUNG",pos:"noun",lv:"A2",me:"The soft part inside the mouth used for tasting and speaking",mv:"Lưỡi",ee:"The food burned my tongue.",ev:"Thức ăn làm bỏng lưỡi tôi.",c:"mother tongue|tongue tied|bite your tongue",s:"",a:"",t:"health|daily-life|food-cooking"},

{w:"tooth",i:"/tuːθ/",p:"TOOTH",pos:"noun",lv:"A1",me:"One of the hard white structures in the mouth for biting",mv:"Răng (số ít)",ee:"The child lost a tooth yesterday.",ev:"Đứa trẻ rụng một chiếc răng hôm qua.",c:"tooth ache|tooth brush|tooth paste|sweet tooth",s:"molar|fang",a:"",t:"health|daily-life"},
{w:"top",i:"/tɑːp/",p:"TAHP",pos:"noun,adjective",lv:"A1",me:"The highest point or surface of something",mv:"Đỉnh, trên cùng",ee:"The cat climbed to the top of the tree.",ev:"Con mèo leo lên đỉnh cây.",c:"on top of|top floor|from top to bottom",s:"peak|summit|upper",a:"bottom|base",t:"daily-life|environment-nature|housing-home"},
{w:"touch",i:"/tʌtʃ/",p:"TUCH",pos:"verb,noun",lv:"A2",me:"To put your hand or finger on something",mv:"Chạm, sờ, đụng",ee:"Do not touch the hot stove.",ev:"Đừng chạm vào bếp nóng.",c:"keep in touch|touch screen|soft touch",s:"feel|contact|handle",a:"avoid|release",t:"daily-life|technology|social-relationships"},
{w:"tough",i:"/tʌf/",p:"TUF",pos:"adjective",lv:"A2",me:"Strong and not easily broken; difficult",mv:"Cứng, dai; khó khăn",ee:"This meat is too tough to eat.",ev:"Miếng thịt này quá dai để ăn.",c:"tough time|tough guy|tough decision",s:"hard|strong|difficult|durable",a:"easy|soft|tender|weak",t:"daily-life|food-cooking|emotion-personality"},
{w:"town",i:"/taʊn/",p:"TOWN",pos:"noun",lv:"A1",me:"A place with houses and buildings, smaller than a city",mv:"Thị trấn",ee:"I grew up in a small town.",ev:"Tôi lớn lên ở một thị trấn nhỏ.",c:"town center|home town|town hall|go to town",s:"village|settlement|community",a:"city|countryside",t:"daily-life|housing-home|travel"},
{w:"toy",i:"/tɔɪ/",p:"TOY",pos:"noun",lv:"A1",me:"An object for children to play with",mv:"Đồ chơi",ee:"The children played with their toys.",ev:"Bọn trẻ chơi với đồ chơi của chúng.",c:"toy shop|toy box|toy car",s:"plaything|game",a:"",t:"daily-life|shopping-consumer|social-relationships"},
{w:"trip",i:"/trɪp/",p:"TRIP",pos:"noun,verb",lv:"A1",me:"A journey to a place and back; to stumble",mv:"Chuyến đi; vấp ngã",ee:"We are planning a trip to the beach.",ev:"Chúng tôi đang lên kế hoạch chuyến đi biển.",c:"road trip|business trip|day trip|trip over",s:"journey|voyage|travel|stumble",a:"stay",t:"travel|daily-life"},
{w:"trouble",i:"/ˈtrʌb.əl/",p:"TRUH-buhl",pos:"noun,verb",lv:"A2",me:"Problems or difficulties; to cause worry",mv:"Rắc rối, vấn đề",ee:"He got into trouble at school.",ev:"Anh ấy gặp rắc rối ở trường.",c:"in trouble|no trouble|trouble maker|ask for trouble",s:"problem|difficulty|issue|worry",a:"ease|peace|solution",t:"daily-life|education|emotion-personality"},
{w:"true",i:"/truː/",p:"TROO",pos:"adjective",lv:"A1",me:"In agreement with fact; not false",mv:"Đúng, thật, thực sự",ee:"Is it true that you are moving?",ev:"Có đúng là bạn sắp chuyển nhà không?",c:"come true|true story|true or false",s:"correct|real|genuine|accurate",a:"false|untrue|fake",t:"daily-life|education|communication"},
{w:"trust",i:"/trʌst/",p:"TRUST",pos:"verb,noun",lv:"A2",me:"To believe that someone is honest and reliable",mv:"Tin tưởng, sự tin tưởng",ee:"I trust my best friend completely.",ev:"Tôi tin tưởng bạn thân hoàn toàn.",c:"trust me|build trust|trust worthy",s:"believe|rely|faith|confidence",a:"distrust|doubt|suspect",t:"social-relationships|daily-life|emotion-personality"},

{w:"ugly",i:"/ˈʌɡ.li/",p:"UG-lee",pos:"adjective",lv:"A2",me:"Unpleasant to look at; not attractive",mv:"Xấu xí",ee:"The old building looked ugly.",ev:"Tòa nhà cũ trông xấu xí.",c:"ugly duckling|ugly truth",s:"unattractive|hideous|unsightly",a:"beautiful|pretty|handsome",t:"daily-life|emotion-personality|housing-home"},
{w:"uncle",i:"/ˈʌŋ.kəl/",p:"UNG-kuhl",pos:"noun",lv:"A1",me:"The brother of your mother or father",mv:"Chú, bác, cậu",ee:"My uncle lives in another city.",ev:"Chú tôi sống ở thành phố khác.",c:"uncle and aunt",s:"relative|kin",a:"aunt",t:"social-relationships|daily-life"},
{w:"until",i:"/ʌnˈtɪl/",p:"un-TIL",pos:"preposition,conjunction",lv:"A1",me:"Up to a particular time or event",mv:"Cho đến khi",ee:"I will wait until you come back.",ev:"Tôi sẽ đợi cho đến khi bạn quay lại.",c:"until now|until then|not until",s:"till|up to|before",a:"since|from",t:"daily-life|communication"},
{w:"usual",i:"/ˈjuː.ʒu.əl/",p:"YOO-zhoo-uhl",pos:"adjective",lv:"A2",me:"Happening most often; normal or typical",mv:"Thường, bình thường",ee:"I took my usual route to work.",ev:"Tôi đi đường bình thường đến chỗ làm.",c:"as usual|the usual|usual time",s:"normal|typical|regular|ordinary",a:"unusual|rare|strange",t:"daily-life"},
{w:"village",i:"/ˈvɪl.ɪdʒ/",p:"VIL-ij",pos:"noun",lv:"A2",me:"A small group of houses in a rural area",mv:"Làng, ngôi làng",ee:"My grandmother lives in a quiet village.",ev:"Bà tôi sống ở một ngôi làng yên tĩnh.",c:"fishing village|village life|small village",s:"hamlet|settlement|community",a:"city|town",t:"daily-life|housing-home|travel|environment-nature"},
{w:"voice",i:"/vɔɪs/",p:"VOYS",pos:"noun",lv:"A1",me:"The sound produced when speaking or singing",mv:"Giọng nói, tiếng nói",ee:"She has a beautiful singing voice.",ev:"Cô ấy có giọng hát hay.",c:"loud voice|voice mail|raise your voice|tone of voice",s:"tone|speech|sound",a:"silence",t:"daily-life|communication|art-culture"},
{w:"wall",i:"/wɔːl/",p:"WAWL",pos:"noun",lv:"A1",me:"A vertical structure that divides or encloses an area",mv:"Tường, bức tường",ee:"There is a clock on the wall.",ev:"Có một chiếc đồng hồ trên tường.",c:"brick wall|wall paper|stone wall|hit a wall",s:"barrier|partition|fence",a:"opening|doorway",t:"housing-home|daily-life"},
{w:"warm",i:"/wɔːrm/",p:"WORM",pos:"adjective,verb",lv:"A1",me:"Having a comfortable level of heat; to make or become warm",mv:"Ấm, ấm áp",ee:"Put on a warm coat before going out.",ev:"Mặc áo ấm trước khi ra ngoài.",c:"warm up|warm weather|warm welcome|keep warm",s:"hot|cozy|mild|heated",a:"cold|cool|chilly",t:"daily-life|environment-nature|clothing-fashion"},
{w:"wash",i:"/wɑːʃ/",p:"WAHSH",pos:"verb,noun",lv:"A1",me:"To clean something with water and soap",mv:"Rửa, giặt",ee:"Please wash your hands before eating.",ev:"Hãy rửa tay trước khi ăn.",c:"wash hands|car wash|wash up|wash machine",s:"clean|rinse|scrub",a:"dirty|soil|stain",t:"daily-life|health|housing-home"},
{w:"wave",i:"/weɪv/",p:"WAYV",pos:"noun,verb",lv:"A2",me:"A raised line of water on the sea; to move the hand to greet",mv:"Sóng; vẫy tay",ee:"She waved goodbye from the window.",ev:"Cô ấy vẫy tay tạm biệt từ cửa sổ.",c:"wave goodbye|heat wave|wave length|ocean wave",s:"billow|surge|gesture|signal",a:"",t:"environment-nature|daily-life|social-relationships|travel"},
];

fs.writeFileSync(p.join(__dirname,'w82-a1-everyday-fill10.js'),
'module.exports={words:'+JSON.stringify(W)+'};');
console.log('w82-a1-everyday-fill10.js created:',W.length,'words');