const fs=require('fs');const p=require('path');
const W=[
{w:"safeguard",i:"/ˈseɪf.ɡɑːrd/",p:"SAYF-gard",pos:"verb",lv:"B2",me:"To protect something from harm or damage",mv:"Bảo vệ, giữ gìn",ee:"The new policy aims to safeguard consumer data from breaches.",ev:"Chính sách mới nhằm bảo vệ dữ liệu người tiêu dùng khỏi bị xâm phạm.",c:"safeguard against|safeguard interests|safeguard privacy",s:"protect|defend|shield",a:"endanger|jeopardize|expose",t:"law-government|technology|work-business|academic-ielts"},
{w:"sanction",i:"/ˈsæŋk.ʃən/",p:"SANGK-shun",pos:"verb",lv:"B2",me:"To officially approve or impose a penalty on",mv:"Phê chuẩn; trừng phạt",ee:"The government sanctioned the trade agreement after months of negotiation.",ev:"Chính phủ phê chuẩn hiệp định thương mại sau nhiều tháng đàm phán.",c:"sanction a decision|impose sanctions|sanction against",s:"authorize|approve|penalize",a:"prohibit|forbid|reject",t:"law-government|finance|academic-ielts|work-business"},
{w:"scrutinize",i:"/ˈskruː.tə.naɪz/",p:"SKROO-tuh-nyz",pos:"verb",lv:"B2",me:"To examine or inspect closely and thoroughly",mv:"Xem xét kỹ lưỡng, soi xét",ee:"The auditors scrutinized every financial transaction for irregularities.",ev:"Các kiểm toán viên xem xét kỹ lưỡng mọi giao dịch tài chính để tìm sai phạm.",c:"scrutinize closely|scrutinize the data|scrutinize a report",s:"examine|inspect|analyze",a:"overlook|ignore|neglect",t:"finance|law-government|academic-ielts|work-business"},
{w:"seize",i:"/siːz/",p:"SEEZ",pos:"verb",lv:"B2",me:"To take hold of suddenly and forcibly; to take possession of",mv:"Nắm bắt, chiếm giữ, tịch thu",ee:"Police seized illegal goods during the raid.",ev:"Cảnh sát tịch thu hàng hóa bất hợp pháp trong cuộc đột kích.",c:"seize an opportunity|seize control|seize assets",s:"grab|capture|confiscate",a:"release|relinquish|surrender",t:"law-government|work-business|academic-ielts|finance"},
{w:"signify",i:"/ˈsɪɡ.nə.faɪ/",p:"SIG-nuh-fy",pos:"verb",lv:"B2",me:"To be a sign of something; to indicate or mean",mv:"Biểu thị, có nghĩa là",ee:"A green light signifies that the system is operating normally.",ev:"Đèn xanh biểu thị rằng hệ thống đang hoạt động bình thường.",c:"signify importance|signify a change|signify meaning",s:"indicate|represent|denote",a:"conceal|obscure|hide",t:"academic-ielts|science|communication|programming-dev"},
{w:"simplify",i:"/ˈsɪm.plə.faɪ/",p:"SIM-pluh-fy",pos:"verb",lv:"B2",me:"To make something easier to do or understand",mv:"Đơn giản hóa",ee:"We need to simplify the user interface to improve the experience.",ev:"Chúng ta cần đơn giản hóa giao diện người dùng để cải thiện trải nghiệm.",c:"simplify the process|simplify a formula|simplify code",s:"streamline|reduce|clarify",a:"complicate|complexify|elaborate",t:"programming-dev|technology|education|work-business"},
{w:"speculate",i:"/ˈspek.jə.leɪt/",p:"SPEK-yoo-layt",pos:"verb",lv:"B2",me:"To form a theory without firm evidence; to invest in risky ventures",mv:"Suy đoán; đầu cơ",ee:"Analysts speculate that the company will announce a merger soon.",ev:"Các nhà phân tích suy đoán rằng công ty sẽ sớm công bố sáp nhập.",c:"speculate about|speculate on|speculate that",s:"conjecture|guess|theorize",a:"confirm|verify|prove",t:"finance|academic-ielts|work-business|science"},
{w:"stabilize",i:"/ˈsteɪ.bə.laɪz/",p:"STAY-buh-lyz",pos:"verb",lv:"B2",me:"To make or become stable; to stop changing or fluctuating",mv:"Ổn định hóa",ee:"The central bank intervened to stabilize the currency.",ev:"Ngân hàng trung ương can thiệp để ổn định đồng tiền.",c:"stabilize the economy|stabilize prices|stabilize a patient",s:"steady|balance|secure",a:"destabilize|upset|disrupt",t:"finance|health|science|academic-ielts"},
{w:"stimulate",i:"/ˈstɪm.jə.leɪt/",p:"STIM-yoo-layt",pos:"verb",lv:"B2",me:"To encourage or arouse activity or interest in something",mv:"Kích thích, thúc đẩy",ee:"The government introduced tax cuts to stimulate economic growth.",ev:"Chính phủ đưa ra cắt giảm thuế để kích thích tăng trưởng kinh tế.",c:"stimulate growth|stimulate demand|stimulate the economy",s:"encourage|boost|promote",a:"discourage|suppress|inhibit",t:"finance|science|health|academic-ielts"},
{w:"stipulate",i:"/ˈstɪp.jə.leɪt/",p:"STIP-yoo-layt",pos:"verb",lv:"C1",me:"To specify a condition or requirement as part of an agreement",mv:"Quy định, đặt điều kiện",ee:"The contract stipulates that payment must be made within 30 days.",ev:"Hợp đồng quy định rằng thanh toán phải được thực hiện trong vòng 30 ngày.",c:"stipulate conditions|stipulate in a contract|stipulate that",s:"specify|require|mandate",a:"waive|overlook|ignore",t:"law-government|work-business|finance|academic-ielts"},

{w:"subordinate",i:"/səˈbɔːr.dən.eɪt/",p:"suh-BOR-duh-nayt",pos:"verb",lv:"C1",me:"To treat something as less important than something else",mv:"Phụ thuộc hóa, đặt xuống dưới",ee:"She refused to subordinate her career goals to anyone else's expectations.",ev:"Cô ấy từ chối đặt mục tiêu nghề nghiệp của mình dưới kỳ vọng của người khác.",c:"subordinate to|subordinate interests|subordinate a clause",s:"demote|lower|subject",a:"elevate|promote|prioritize",t:"work-business|academic-ielts|law-government|education"},
{w:"subsidize",i:"/ˈsʌb.sə.daɪz/",p:"SUB-suh-dyz",pos:"verb",lv:"B2",me:"To support financially by paying part of the cost",mv:"Trợ cấp, tài trợ",ee:"The government subsidizes public transportation to keep fares low.",ev:"Chính phủ trợ cấp giao thông công cộng để giữ giá vé thấp.",c:"subsidize housing|subsidize farmers|heavily subsidized",s:"fund|finance|sponsor",a:"tax|charge|defund",t:"finance|law-government|academic-ielts|education"},
{w:"supplement",i:"/ˈsʌp.lɪ.ment/",p:"SUP-luh-ment",pos:"verb",lv:"B2",me:"To add something extra to enhance or complete",mv:"Bổ sung, bổ trợ",ee:"She supplements her income by freelancing on weekends.",ev:"Cô ấy bổ sung thu nhập bằng cách làm freelance vào cuối tuần.",c:"supplement income|supplement with|supplement a diet",s:"add to|enhance|augment",a:"reduce|diminish|deplete",t:"health|finance|work-business|academic-ielts"},
{w:"suppress",i:"/səˈpres/",p:"suh-PRES",pos:"verb",lv:"B2",me:"To forcibly put an end to; to prevent from being expressed",mv:"Đàn áp, kìm nén",ee:"The regime attempted to suppress all forms of political dissent.",ev:"Chế độ cố gắng đàn áp mọi hình thức bất đồng chính trị.",c:"suppress information|suppress emotions|suppress a revolt",s:"restrain|stifle|quash",a:"encourage|express|release",t:"law-government|academic-ielts|health|communication"},
{w:"surpass",i:"/sɚˈpæs/",p:"ser-PAS",pos:"verb",lv:"B2",me:"To exceed or be greater than something",mv:"Vượt qua, vượt trội",ee:"This year's sales surpassed all previous records.",ev:"Doanh số năm nay vượt qua tất cả các kỷ lục trước đó.",c:"surpass expectations|surpass a record|surpass competitors",s:"exceed|outdo|outperform",a:"fall behind|trail|underperform",t:"work-business|finance|academic-ielts|science"},
{w:"surrender",i:"/səˈren.dɚ/",p:"suh-REN-der",pos:"verb",lv:"B2",me:"To give up possession or control of something; to yield",mv:"Đầu hàng, giao nộp",ee:"The company was forced to surrender its patent rights after the lawsuit.",ev:"Công ty bị buộc phải giao nộp quyền sáng chế sau vụ kiện.",c:"surrender to|surrender control|surrender arms",s:"yield|relinquish|concede",a:"resist|fight|defend",t:"law-government|work-business|academic-ielts|communication"},
{w:"sustain",i:"/səˈsteɪn/",p:"suh-STAYN",pos:"verb",lv:"B2",me:"To maintain or keep going over a period of time; to suffer or endure",mv:"Duy trì, chịu đựng",ee:"The economy needs strong policies to sustain long-term growth.",ev:"Nền kinh tế cần chính sách mạnh để duy trì tăng trưởng dài hạn.",c:"sustain growth|sustain injuries|sustain development",s:"maintain|uphold|endure",a:"abandon|discontinue|halt",t:"finance|academic-ielts|science|health"},
{w:"tackle",i:"/ˈtæk.əl/",p:"TAK-uhl",pos:"verb",lv:"B2",me:"To make determined efforts to deal with a problem or task",mv:"Giải quyết, xử lý",ee:"The team tackled the bug by reviewing the entire codebase.",ev:"Nhóm giải quyết lỗi bằng cách xem xét toàn bộ mã nguồn.",c:"tackle a problem|tackle an issue|tackle challenges",s:"address|confront|handle",a:"avoid|ignore|evade",t:"work-business|programming-dev|academic-ielts|education"},
{w:"testify",i:"/ˈtes.tə.faɪ/",p:"TES-tuh-fy",pos:"verb",lv:"B2",me:"To give evidence or bear witness, especially in a court of law",mv:"Làm chứng, chứng thực",ee:"The witness testified that she saw the suspect at the scene.",ev:"Nhân chứng làm chứng rằng cô ấy nhìn thấy nghi phạm tại hiện trường.",c:"testify in court|testify against|testify under oath",s:"witness|attest|declare",a:"deny|recant|retract",t:"law-government|academic-ielts|communication"},
{w:"tolerate",i:"/ˈtɑː.lə.reɪt/",p:"TAH-luh-rayt",pos:"verb",lv:"B2",me:"To allow or accept something without interference; to endure",mv:"Chịu đựng, dung thứ",ee:"The manager will not tolerate any form of workplace harassment.",ev:"Quản lý sẽ không dung thứ bất kỳ hình thức quấy rối nào tại nơi làm việc.",c:"tolerate behavior|tolerate pain|tolerate differences",s:"endure|accept|bear",a:"reject|oppose|resist",t:"work-business|social-relationships|health|academic-ielts"},

{w:"transcend",i:"/trænˈsend/",p:"tran-SEND",pos:"verb",lv:"C1",me:"To go beyond the limits of something; to surpass",mv:"Vượt lên trên, siêu việt",ee:"Great art has the power to transcend cultural boundaries.",ev:"Nghệ thuật vĩ đại có sức mạnh vượt lên trên ranh giới văn hóa.",c:"transcend boundaries|transcend limitations|transcend expectations",s:"surpass|exceed|go beyond",a:"conform|stay within|submit to",t:"academic-ielts|education|science|communication"},
{w:"underestimate",i:"/ˌʌn.dɚˈes.tə.meɪt/",p:"un-der-ES-tuh-mayt",pos:"verb",lv:"B2",me:"To estimate something as being less than its actual value or size",mv:"Đánh giá thấp",ee:"Never underestimate the complexity of migrating a legacy system.",ev:"Đừng bao giờ đánh giá thấp sự phức tạp của việc di chuyển hệ thống cũ.",c:"underestimate the cost|underestimate the risk|underestimate someone",s:"undervalue|underrate|misjudge",a:"overestimate|overrate|overvalue",t:"work-business|programming-dev|finance|academic-ielts"},
{w:"undermine",i:"/ˌʌn.dɚˈmaɪn/",p:"un-der-MYN",pos:"verb",lv:"B2",me:"To gradually weaken or damage something",mv:"Phá hoại, làm suy yếu",ee:"Constant criticism can undermine a person's confidence.",ev:"Sự chỉ trích liên tục có thể làm suy yếu sự tự tin của một người.",c:"undermine authority|undermine confidence|undermine efforts",s:"weaken|sabotage|erode",a:"strengthen|reinforce|support",t:"work-business|social-relationships|academic-ielts|law-government"},
{w:"unify",i:"/ˈjuː.nə.faɪ/",p:"YOO-nuh-fy",pos:"verb",lv:"B2",me:"To bring together to form a single unit or whole",mv:"Thống nhất, hợp nhất",ee:"The new API was designed to unify all microservices under one gateway.",ev:"API mới được thiết kế để thống nhất tất cả microservices dưới một cổng.",c:"unify a team|unify standards|unify the country",s:"unite|merge|consolidate",a:"divide|separate|fragment",t:"programming-dev|law-government|work-business|academic-ielts"},
{w:"upgrade",i:"/ʌpˈɡreɪd/",p:"up-GRAYD",pos:"verb",lv:"B2",me:"To raise to a higher standard or improve quality",mv:"Nâng cấp",ee:"We plan to upgrade the server infrastructure next quarter.",ev:"Chúng tôi dự định nâng cấp hạ tầng máy chủ vào quý tới.",c:"upgrade software|upgrade a system|upgrade to premium",s:"improve|enhance|update",a:"downgrade|degrade|deteriorate",t:"technology|programming-dev|work-business|education"},
{w:"uphold",i:"/ʌpˈhoʊld/",p:"up-HOHLD",pos:"verb",lv:"B2",me:"To maintain or support a principle, law, or decision",mv:"Duy trì, ủng hộ, giữ vững",ee:"The court upheld the original ruling on data privacy.",ev:"Tòa án giữ vững phán quyết ban đầu về quyền riêng tư dữ liệu.",c:"uphold the law|uphold a decision|uphold standards",s:"maintain|support|defend",a:"overturn|reject|violate",t:"law-government|academic-ielts|work-business|education"},
{w:"utilize",i:"/ˈjuː.tə.laɪz/",p:"YOO-tuh-lyz",pos:"verb",lv:"B2",me:"To make practical and effective use of something",mv:"Sử dụng, tận dụng",ee:"The project utilizes machine learning to predict user behavior.",ev:"Dự án tận dụng học máy để dự đoán hành vi người dùng.",c:"utilize resources|utilize technology|fully utilize",s:"use|employ|apply",a:"waste|neglect|disregard",t:"technology|programming-dev|work-business|academic-ielts"},
{w:"verify",i:"/ˈver.ə.faɪ/",p:"VER-uh-fy",pos:"verb",lv:"B2",me:"To make sure or demonstrate that something is true or accurate",mv:"Xác minh, kiểm chứng",ee:"Please verify your email address before logging in.",ev:"Vui lòng xác minh địa chỉ email trước khi đăng nhập.",c:"verify identity|verify information|verify a claim",s:"confirm|validate|authenticate",a:"disprove|falsify|deny",t:"technology|programming-dev|law-government|academic-ielts"},
{w:"violate",i:"/ˈvaɪ.ə.leɪt/",p:"VY-uh-layt",pos:"verb",lv:"B2",me:"To break or fail to comply with a rule, law, or agreement",mv:"Vi phạm, xâm phạm",ee:"The company was fined for violating environmental regulations.",ev:"Công ty bị phạt vì vi phạm các quy định về môi trường.",c:"violate the law|violate a contract|violate rights",s:"breach|break|infringe",a:"comply|obey|respect",t:"law-government|academic-ielts|work-business|finance"},
{w:"visualize",i:"/ˈvɪʒ.u.ə.laɪz/",p:"VIZH-oo-uh-lyz",pos:"verb",lv:"B2",me:"To form a mental image of something; to display data graphically",mv:"Hình dung, trực quan hóa",ee:"The dashboard helps visualize real-time performance metrics.",ev:"Bảng điều khiển giúp trực quan hóa các chỉ số hiệu suất thời gian thực.",c:"visualize data|visualize the future|visualize a concept",s:"imagine|picture|illustrate",a:"ignore|overlook|disregard",t:"programming-dev|technology|science|academic-ielts"},
];

fs.writeFileSync(p.join(__dirname,'w84-b2-verbs-sz.js'),
'module.exports={words:'+JSON.stringify(W)+'};');
console.log('w84-b2-verbs-sz.js created:',W.length,'words');