const fs=require('fs');const p=require('path');
const W=[
{w:"abandon",i:"/əˈbæn.dən/",p:"uh-BAN-duhn",pos:"verb",lv:"B1",me:"To leave behind or give up completely",mv:"Từ bỏ, bỏ rơi",ee:"They had to abandon the project due to lack of funding.",ev:"Họ phải từ bỏ dự án vì thiếu kinh phí.",c:"abandon a plan|abandon hope|abandon ship",s:"give up|desert|forsake",a:"keep|maintain|continue",t:"work-business|academic-ielts|communication"},
{w:"absorb",i:"/əbˈzɔːrb/",p:"uhb-ZORB",pos:"verb",lv:"B2",me:"To take in or soak up a substance, knowledge, or cost",mv:"Hấp thụ, tiếp thu",ee:"Plants absorb carbon dioxide from the air.",ev:"Cây hấp thụ khí CO2 từ không khí.",c:"absorb information|absorb the cost|absorb moisture",s:"soak up|take in|assimilate",a:"emit|release|repel",t:"science|education|finance|academic-ielts"},
{w:"abuse",i:"/əˈbjuːz/",p:"uh-BYOOZ",pos:"verb",lv:"B2",me:"To use something wrongly or to treat someone cruelly",mv:"Lạm dụng, ngược đãi",ee:"He was accused of abusing his power as manager.",ev:"Anh ta bị cáo buộc lạm dụng quyền lực khi làm quản lý.",c:"abuse power|abuse drugs|child abuse",s:"misuse|exploit|mistreat",a:"respect|protect|cherish",t:"law-government|academic-ielts|communication"},
{w:"accelerate",i:"/əkˈsel.ə.reɪt/",p:"uhk-SEL-uh-rayt",pos:"verb",lv:"B2",me:"To increase in speed or cause something to happen faster",mv:"Tăng tốc, đẩy nhanh",ee:"The company plans to accelerate its digital transformation.",ev:"Công ty dự định đẩy nhanh quá trình chuyển đổi số.",c:"accelerate growth|accelerate the process|accelerate change",s:"speed up|hasten|quicken",a:"slow down|decelerate|delay",t:"work-business|technology|science|academic-ielts"},
{w:"accommodate",i:"/əˈkɑː.mə.deɪt/",p:"uh-KAH-muh-dayt",pos:"verb",lv:"B2",me:"To provide space or to adjust to meet someone's needs",mv:"Đáp ứng, cung cấp chỗ ở",ee:"The hotel can accommodate up to 500 guests.",ev:"Khách sạn có thể đáp ứng tới 500 khách.",c:"accommodate needs|accommodate guests|accommodate changes",s:"house|fit|adjust to",a:"reject|refuse|exclude",t:"work-business|travel|academic-ielts|communication"},
{w:"accumulate",i:"/əˈkjuː.mjə.leɪt/",p:"uh-KYOO-myuh-layt",pos:"verb",lv:"B2",me:"To gather or collect over time",mv:"Tích lũy, tích góp",ee:"She accumulated a lot of experience over the years.",ev:"Cô ấy tích lũy nhiều kinh nghiệm qua nhiều năm.",c:"accumulate wealth|accumulate data|accumulate debt",s:"gather|collect|amass",a:"spend|disperse|scatter",t:"finance|academic-ielts|work-business"},
{w:"acknowledge",i:"/əkˈnɑː.lɪdʒ/",p:"uhk-NAH-lij",pos:"verb",lv:"B2",me:"To accept or admit the truth or existence of something",mv:"Thừa nhận, công nhận",ee:"He acknowledged that the team had made a mistake.",ev:"Anh ấy thừa nhận rằng đội đã mắc sai lầm.",c:"acknowledge a mistake|acknowledge receipt|widely acknowledged",s:"admit|recognize|accept",a:"deny|ignore|reject",t:"work-business|communication|academic-ielts"},
{w:"acquire",i:"/əˈkwaɪər/",p:"uh-KWYRE",pos:"verb",lv:"B2",me:"To obtain or gain possession of something",mv:"Có được, mua lại",ee:"The company acquired a smaller competitor last year.",ev:"Công ty mua lại một đối thủ nhỏ hơn năm ngoái.",c:"acquire skills|acquire knowledge|acquire a company",s:"obtain|gain|purchase",a:"lose|sell|forfeit",t:"work-business|finance|education|academic-ielts"},
{w:"administer",i:"/ədˈmɪn.ɪ.stər/",p:"uhd-MIN-ih-ster",pos:"verb",lv:"B2",me:"To manage or be responsible for the operation of something",mv:"Quản lý, điều hành",ee:"She administers the scholarship program at the university.",ev:"Cô ấy quản lý chương trình học bổng tại trường đại học.",c:"administer a program|administer medicine|administer a test",s:"manage|run|oversee",a:"neglect|mismanage",t:"work-business|education|law-government|academic-ielts"},
{w:"advocate",i:"/ˈæd.və.keɪt/",p:"AD-vuh-kayt",pos:"verb",lv:"B2",me:"To publicly support or recommend a cause or policy",mv:"Ủng hộ, vận động",ee:"She advocates for equal rights in the workplace.",ev:"Cô ấy vận động cho quyền bình đẳng tại nơi làm việc.",c:"advocate for|strongly advocate|advocate change",s:"support|promote|champion",a:"oppose|discourage|reject",t:"law-government|academic-ielts|communication"},

{w:"allocate",i:"/ˈæl.ə.keɪt/",p:"AL-uh-kayt",pos:"verb",lv:"B2",me:"To distribute resources or duties for a particular purpose",mv:"Phân bổ, cấp phát",ee:"The manager allocated tasks to each team member.",ev:"Quản lý phân bổ nhiệm vụ cho từng thành viên.",c:"allocate resources|allocate funds|allocate memory",s:"assign|distribute|allot",a:"withhold|retain|collect",t:"work-business|finance|programming-dev|academic-ielts"},
{w:"alter",i:"/ˈɑːl.tər/",p:"AWL-ter",pos:"verb",lv:"B1",me:"To change or make different",mv:"Thay đổi, sửa đổi",ee:"We need to alter the design before production.",ev:"Chúng ta cần thay đổi thiết kế trước khi sản xuất.",c:"alter the course|alter a plan|alter significantly",s:"change|modify|adjust",a:"preserve|maintain|keep",t:"work-business|technology|academic-ielts"},
{w:"amend",i:"/əˈmend/",p:"uh-MEND",pos:"verb",lv:"B2",me:"To make changes to a document or law to improve it",mv:"Sửa đổi, bổ sung",ee:"The parliament voted to amend the constitution.",ev:"Quốc hội bỏ phiếu sửa đổi hiến pháp.",c:"amend the law|amend a contract|amend the constitution",s:"revise|modify|correct",a:"preserve|maintain",t:"law-government|work-business|academic-ielts"},
{w:"anticipate",i:"/ænˈtɪs.ə.peɪt/",p:"an-TIS-uh-payt",pos:"verb",lv:"B2",me:"To expect or predict something will happen",mv:"Dự đoán, lường trước",ee:"We anticipate a rise in demand next quarter.",ev:"Chúng tôi dự đoán nhu cầu sẽ tăng quý tới.",c:"anticipate problems|anticipate demand|widely anticipated",s:"expect|predict|foresee",a:"overlook|ignore|disregard",t:"work-business|finance|academic-ielts"},
{w:"appeal",i:"/əˈpiːl/",p:"uh-PEEL",pos:"verb",lv:"B1",me:"To make a serious request or to attract interest",mv:"Kêu gọi, kháng cáo, hấp dẫn",ee:"The charity appealed for donations after the disaster.",ev:"Tổ chức từ thiện kêu gọi quyên góp sau thảm họa.",c:"appeal to|appeal against|appeal for",s:"request|plead|attract",a:"repel|deter|discourage",t:"law-government|communication|academic-ielts"},
{w:"appoint",i:"/əˈpɔɪnt/",p:"uh-POINT",pos:"verb",lv:"B2",me:"To officially choose someone for a position or role",mv:"Bổ nhiệm, chỉ định",ee:"The board appointed a new CEO last month.",ev:"Hội đồng bổ nhiệm CEO mới tháng trước.",c:"appoint a manager|appoint a committee|newly appointed",s:"assign|designate|nominate",a:"dismiss|fire|remove",t:"work-business|law-government|academic-ielts"},
{w:"arise",i:"/əˈraɪz/",p:"uh-RYZE",pos:"verb",lv:"B2",me:"To come into existence or to occur",mv:"Phát sinh, nảy sinh",ee:"Problems may arise if we do not plan carefully.",ev:"Vấn đề có thể phát sinh nếu chúng ta không lên kế hoạch cẩn thận.",c:"arise from|problems arise|issues arise",s:"emerge|occur|appear",a:"disappear|vanish|cease",t:"work-business|law-government|academic-ielts"},
{w:"assemble",i:"/əˈsem.bəl/",p:"uh-SEM-buhl",pos:"verb",lv:"B2",me:"To gather together or to put parts together",mv:"Tập hợp, lắp ráp",ee:"Workers assemble the components on the factory floor.",ev:"Công nhân lắp ráp các linh kiện trên sàn nhà máy.",c:"assemble a team|assemble parts|assemble data",s:"gather|construct|build",a:"disassemble|scatter|disperse",t:"work-business|technology|academic-ielts"},
{w:"assert",i:"/əˈsɜːrt/",p:"uh-SURT",pos:"verb",lv:"B2",me:"To state something confidently and forcefully",mv:"Khẳng định, quả quyết",ee:"She asserted her right to speak at the meeting.",ev:"Cô ấy khẳng định quyền phát biểu tại cuộc họp.",c:"assert authority|assert a claim|assert oneself",s:"declare|claim|state",a:"deny|retract|withdraw",t:"communication|law-government|academic-ielts"},
{w:"assess",i:"/əˈses/",p:"uh-SES",pos:"verb",lv:"B1",me:"To evaluate or estimate the nature, quality, or value of something",mv:"Đánh giá, thẩm định",ee:"The teacher assessed the students' progress at the end of term.",ev:"Giáo viên đánh giá tiến bộ của học sinh cuối kỳ.",c:"assess the situation|assess risk|assess performance",s:"evaluate|judge|appraise",a:"ignore|overlook|neglect",t:"education|work-business|academic-ielts"},

{w:"attribute",i:"/əˈtrɪb.juːt/",p:"uh-TRIB-yoot",pos:"verb",lv:"B2",me:"To regard something as being caused by a particular factor",mv:"Quy cho, gán cho",ee:"She attributes her success to hard work and discipline.",ev:"Cô ấy quy thành công cho sự chăm chỉ và kỷ luật.",c:"attribute to|attribute success|attribute the cause",s:"ascribe|credit|assign",a:"dissociate|disconnect",t:"academic-ielts|education|science"},
{w:"authorize",i:"/ˈɑː.θər.aɪz/",p:"AW-thuh-ryze",pos:"verb",lv:"B2",me:"To give official permission for something",mv:"Ủy quyền, cho phép",ee:"Only the director can authorize this payment.",ev:"Chỉ giám đốc mới có thể ủy quyền khoản thanh toán này.",c:"authorize access|authorize payment|authorized personnel",s:"permit|approve|sanction",a:"forbid|prohibit|deny",t:"work-business|law-government|programming-dev|finance"},
{w:"bind",i:"/baɪnd/",p:"BYND",pos:"verb",lv:"B2",me:"To tie or fasten tightly, or to impose a legal obligation",mv:"Ràng buộc, buộc",ee:"The contract binds both parties to the agreement.",ev:"Hợp đồng ràng buộc cả hai bên với thỏa thuận.",c:"legally binding|bind together|bind data",s:"tie|fasten|obligate",a:"release|free|unbind",t:"law-government|programming-dev|academic-ielts"},
{w:"boost",i:"/buːst/",p:"BOOST",pos:"verb",lv:"B1",me:"To increase or improve something",mv:"Thúc đẩy, tăng cường",ee:"The new campaign helped boost sales by 20 percent.",ev:"Chiến dịch mới giúp tăng doanh số 20 phần trăm.",c:"boost performance|boost confidence|boost the economy",s:"increase|enhance|improve",a:"reduce|decrease|diminish",t:"work-business|finance|technology|academic-ielts"},
{w:"broadcast",i:"/ˈbrɔːd.kæst/",p:"BRAWD-kast",pos:"verb",lv:"B2",me:"To transmit a program or information by radio, television, or internet",mv:"Phát sóng, truyền tin",ee:"The event will be broadcast live on national television.",ev:"Sự kiện sẽ được phát sóng trực tiếp trên truyền hình quốc gia.",c:"broadcast live|broadcast a message|broadcast news",s:"transmit|air|stream",a:"receive|withhold",t:"communication|technology|academic-ielts"},
{w:"burden",i:"/ˈbɜːr.dən/",p:"BUR-duhn",pos:"verb",lv:"B2",me:"To load someone with something difficult to bear",mv:"Gánh nặng, đè nặng",ee:"We should not burden employees with unnecessary paperwork.",ev:"Chúng ta không nên đè nặng nhân viên với giấy tờ không cần thiết.",c:"burden with|financial burden|burden of proof",s:"weigh down|overload|encumber",a:"relieve|lighten|ease",t:"work-business|law-government|finance|academic-ielts"},
{w:"cease",i:"/siːs/",p:"SEES",pos:"verb",lv:"B2",me:"To stop or come to an end",mv:"Chấm dứt, ngừng",ee:"The factory ceased operations due to safety concerns.",ev:"Nhà máy ngừng hoạt động vì lo ngại an toàn.",c:"cease to exist|cease operations|cease fire",s:"stop|halt|discontinue",a:"begin|start|continue",t:"work-business|law-government|academic-ielts"},
{w:"circulate",i:"/ˈsɜːr.kjə.leɪt/",p:"SUR-kyuh-layt",pos:"verb",lv:"B2",me:"To move or cause to move continuously through a system or among people",mv:"Lưu thông, phổ biến",ee:"The memo was circulated to all departments.",ev:"Bản ghi nhớ được phổ biến đến tất cả các phòng ban.",c:"circulate information|circulate a report|circulate widely",s:"distribute|spread|disseminate",a:"withhold|suppress|contain",t:"communication|work-business|science|academic-ielts"},
{w:"cite",i:"/saɪt/",p:"SYTE",pos:"verb",lv:"B2",me:"To quote or refer to something as evidence or an example",mv:"Trích dẫn, viện dẫn",ee:"The researcher cited several studies to support her argument.",ev:"Nhà nghiên cứu trích dẫn nhiều nghiên cứu để hỗ trợ lập luận.",c:"cite a source|cite an example|cite evidence",s:"quote|reference|mention",a:"ignore|omit",t:"academic-ielts|education|science|law-government"},
{w:"clarify",i:"/ˈklær.ə.faɪ/",p:"KLAIR-uh-fye",pos:"verb",lv:"B1",me:"To make something clearer or easier to understand",mv:"Làm rõ, giải thích rõ",ee:"Could you clarify what you mean by that statement?",ev:"Bạn có thể làm rõ ý bạn muốn nói trong phát biểu đó không?",c:"clarify a point|clarify the situation|clarify the meaning",s:"explain|elucidate|illuminate",a:"confuse|obscure|complicate",t:"communication|education|work-business|academic-ielts"},
];
fs.writeFileSync(p.join(__dirname,'w67-b1-verbs-ad2.js'),
'module.exports={words:'+JSON.stringify(W)+'};');
console.log('w67-b1-verbs-ad2.js created:',W.length,'words');