const fs=require('fs');const p=require('path');
const W=[
{w:"tale",i:"/teɪl/",p:"TAYL",pos:"noun",lv:"B1",me:"A story, especially one that is imaginative or hard to believe",mv:"Câu chuyện, truyện kể",ee:"My grandmother told us a tale about a brave knight.",ev:"Bà tôi kể cho chúng tôi một câu chuyện về một hiệp sĩ dũng cảm.",c:"fairy tale|tell a tale|old wives' tale",s:"story|narrative|legend",a:"fact|truth",t:"art-culture|education|media-entertainment"},
{w:"talent",i:"/ˈtæl.ənt/",p:"TAL-uhnt",pos:"noun",lv:"A2",me:"A natural ability or skill",mv:"Tài năng",ee:"She has a real talent for painting.",ev:"Cô ấy có tài năng thực sự trong hội họa.",c:"talent show|natural talent|talent for",s:"gift|ability|skill",a:"inability|weakness",t:"art-culture|education|work-business"},
{w:"tank",i:"/tæŋk/",p:"TANGK",pos:"noun",lv:"A2",me:"A large container for storing liquid or gas; a heavy armored military vehicle",mv:"Bể chứa; xe tăng",ee:"The fish tank needs to be cleaned every week.",ev:"Bể cá cần được vệ sinh mỗi tuần.",c:"fish tank|fuel tank|tank top",s:"container|reservoir|vessel",a:"",t:"daily-life|environment-nature"},
{w:"tap",i:"/tæp/",p:"TAP",pos:"noun,verb",lv:"A2",me:"A device for controlling the flow of water; to strike lightly",mv:"Vòi nước; gõ nhẹ",ee:"Turn off the tap to save water.",ev:"Tắt vòi nước để tiết kiệm nước.",c:"tap water|tap on|tap into",s:"faucet|knock|pat",a:"",t:"daily-life|environment-nature"},
{w:"target",i:"/ˈtɑːr.ɡɪt/",p:"TAR-git",pos:"noun,verb",lv:"A2",me:"An objective or goal that someone is trying to achieve",mv:"Mục tiêu",ee:"We need to reach our sales target by the end of the month.",ev:"Chúng ta cần đạt mục tiêu doanh số trước cuối tháng.",c:"target audience|hit the target|target market",s:"goal|aim|objective",a:"",t:"work-business|education|sports-fitness"},
{w:"technique",i:"/tɛkˈniːk/",p:"tek-NEEK",pos:"noun",lv:"A2",me:"A particular way of doing something, especially one that requires skill",mv:"Kỹ thuật",ee:"She learned a new painting technique in art class.",ev:"Cô ấy học một kỹ thuật vẽ mới trong lớp mỹ thuật.",c:"technique for|modern technique|breathing technique",s:"method|skill|approach",a:"",t:"education|art-culture|science"},
{w:"temple",i:"/ˈtɛm.pəl/",p:"TEM-puhl",pos:"noun",lv:"A2",me:"A building used for the worship of a god or gods",mv:"Đền, chùa",ee:"We visited an ancient temple during our trip to Japan.",ev:"Chúng tôi thăm một ngôi đền cổ trong chuyến đi Nhật Bản.",c:"Buddhist temple|ancient temple|temple ruins",s:"shrine|sanctuary|pagoda",a:"",t:"travel|art-culture|daily-life"},
{w:"tension",i:"/ˈtɛn.ʃən/",p:"TEN-shuhn",pos:"noun",lv:"B1",me:"A feeling of nervousness or worry; strained relations between people or groups",mv:"Sự căng thẳng",ee:"There is a lot of tension between the two countries.",ev:"Có rất nhiều căng thẳng giữa hai quốc gia.",c:"political tension|muscle tension|ease the tension",s:"stress|strain|pressure",a:"relaxation|calm",t:"social-relationships|health|daily-life"},
{w:"territory",i:"/ˈtɛr.ɪ.tɔːr.i/",p:"TER-ih-tor-ee",pos:"noun",lv:"B1",me:"An area of land under the control of a ruler or state",mv:"Lãnh thổ, vùng đất",ee:"The animal defended its territory from intruders.",ev:"Con vật bảo vệ lãnh thổ của nó khỏi kẻ xâm nhập.",c:"enemy territory|uncharted territory|territorial dispute",s:"region|area|domain",a:"",t:"environment-nature|travel|education"},
{w:"textile",i:"/ˈtɛk.staɪl/",p:"TEK-styl",pos:"noun,adjective",lv:"B2",me:"A type of cloth or woven fabric",mv:"Vải, dệt may",ee:"The region is famous for its textile industry.",ev:"Vùng này nổi tiếng với ngành công nghiệp dệt may.",c:"textile industry|textile factory|textile design",s:"fabric|cloth|material",a:"",t:"work-business|art-culture|daily-life"},

{w:"theme",i:"/θiːm/",p:"THEEM",pos:"noun",lv:"A2",me:"The main subject or idea in a piece of writing, talk, or event",mv:"Chủ đề",ee:"The theme of the conference is climate change.",ev:"Chủ đề của hội nghị là biến đổi khí hậu.",c:"main theme|theme park|theme song",s:"topic|subject|motif",a:"",t:"education|art-culture|media-entertainment"},
{w:"therapy",i:"/ˈθɛr.ə.pi/",p:"THER-uh-pee",pos:"noun",lv:"B1",me:"Treatment intended to relieve or heal a physical or mental condition",mv:"Liệu pháp, trị liệu",ee:"She started therapy to help manage her anxiety.",ev:"Cô ấy bắt đầu trị liệu để giúp kiểm soát lo âu.",c:"physical therapy|speech therapy|therapy session",s:"treatment|healing|rehabilitation",a:"neglect",t:"health|science|daily-life"},
{w:"threat",i:"/θrɛt/",p:"THRET",pos:"noun",lv:"B1",me:"A statement of intention to cause harm; a person or thing likely to cause damage",mv:"Mối đe dọa",ee:"Climate change is a serious threat to the environment.",ev:"Biến đổi khí hậu là mối đe dọa nghiêm trọng đối với môi trường.",c:"security threat|pose a threat|under threat",s:"danger|menace|risk",a:"safety|protection",t:"environment-nature|daily-life|law-government"},
{w:"throat",i:"/θroʊt/",p:"THROHT",pos:"noun",lv:"A2",me:"The passage from the mouth to the stomach or lungs",mv:"Cổ họng",ee:"I have a sore throat and cannot speak well.",ev:"Tôi bị đau họng và không nói rõ được.",c:"sore throat|clear one's throat|throat infection",s:"gullet|neck|windpipe",a:"",t:"health|daily-life"},
{w:"thumb",i:"/θʌm/",p:"THUM",pos:"noun,verb",lv:"A2",me:"The short thick first digit of the hand",mv:"Ngón tay cái",ee:"She gave a thumbs up to show her approval.",ev:"Cô ấy giơ ngón cái lên để thể hiện sự đồng ý.",c:"thumbs up|thumb through|rule of thumb",s:"digit|finger",a:"",t:"daily-life|health"},
{w:"tide",i:"/taɪd/",p:"TYDE",pos:"noun",lv:"B1",me:"The regular rise and fall of the sea level caused by the moon and sun",mv:"Thủy triều",ee:"The tide comes in and goes out twice a day.",ev:"Thủy triều lên và xuống hai lần mỗi ngày.",c:"high tide|low tide|turn the tide",s:"current|flow|wave",a:"",t:"environment-nature|science|travel"},
{w:"timber",i:"/ˈtɪm.bər/",p:"TIM-ber",pos:"noun",lv:"B2",me:"Wood prepared for use in building and carpentry",mv:"Gỗ xẻ",ee:"The house was built using local timber.",ev:"Ngôi nhà được xây bằng gỗ địa phương.",c:"timber frame|timber industry|timber trade",s:"wood|lumber|log",a:"",t:"environment-nature|work-business|daily-life"},
{w:"tissue",i:"/ˈtɪʃ.uː/",p:"TISH-oo",pos:"noun",lv:"A2",me:"A piece of soft thin paper used for wiping; a group of cells in the body",mv:"Khăn giấy; mô (sinh học)",ee:"She grabbed a tissue to wipe her tears.",ev:"Cô ấy lấy một tờ khăn giấy để lau nước mắt.",c:"tissue paper|body tissue|box of tissues",s:"paper|napkin|cell group",a:"",t:"daily-life|health|science"},
{w:"tobacco",i:"/təˈbæk.oʊ/",p:"tuh-BAK-oh",pos:"noun",lv:"B1",me:"A plant whose leaves are dried and used for smoking or chewing",mv:"Thuốc lá",ee:"The government raised taxes on tobacco products.",ev:"Chính phủ tăng thuế đối với các sản phẩm thuốc lá.",c:"tobacco industry|tobacco smoke|chewing tobacco",s:"cigarette|nicotine|smoke",a:"",t:"health|work-business|law-government"},
{w:"tongue",i:"/tʌŋ/",p:"TUNG",pos:"noun",lv:"A2",me:"The muscular organ in the mouth used for tasting and speaking",mv:"Lưỡi",ee:"The food was so hot it burned my tongue.",ev:"Thức ăn nóng quá làm bỏng lưỡi tôi.",c:"mother tongue|tongue-tied|on the tip of one's tongue",s:"language|speech",a:"",t:"daily-life|health|education"},

{w:"tool",i:"/tuːl/",p:"TOOL",pos:"noun",lv:"A2",me:"A device or implement used to carry out a particular function",mv:"Dụng cụ, công cụ",ee:"A hammer is a useful tool for building things.",ev:"Búa là một dụng cụ hữu ích để xây dựng.",c:"power tool|tool kit|tool for",s:"instrument|device|implement",a:"",t:"daily-life|work-business|science"},
{w:"topic",i:"/ˈtɑː.pɪk/",p:"TAH-pik",pos:"noun",lv:"A2",me:"A subject that is discussed or written about",mv:"Chủ đề",ee:"The topic of today's lesson is grammar.",ev:"Chủ đề bài học hôm nay là ngữ pháp.",c:"hot topic|change the topic|topic of discussion",s:"subject|theme|issue",a:"",t:"education|communication|daily-life"},
{w:"torch",i:"/tɔːrtʃ/",p:"TORCH",pos:"noun",lv:"B1",me:"A portable light powered by batteries; a stick with a flame at one end",mv:"Đèn pin; ngọn đuốc",ee:"He used a torch to find his way in the dark.",ev:"Anh ấy dùng đèn pin để tìm đường trong bóng tối.",c:"carry a torch|Olympic torch|torch light",s:"flashlight|lantern|lamp",a:"",t:"daily-life|sports-fitness|travel"},
{w:"tower",i:"/ˈtaʊ.ər/",p:"TOW-er",pos:"noun,verb",lv:"A2",me:"A tall narrow building or structure",mv:"Tháp",ee:"The Eiffel Tower is the most famous landmark in Paris.",ev:"Tháp Eiffel là địa danh nổi tiếng nhất ở Paris.",c:"clock tower|control tower|tower block",s:"turret|spire|skyscraper",a:"",t:"travel|art-culture|daily-life"},
{w:"trace",i:"/treɪs/",p:"TRAYS",pos:"noun,verb",lv:"B1",me:"A mark or sign showing that something has existed; to find or discover by investigation",mv:"Dấu vết; truy tìm",ee:"The police found traces of blood at the crime scene.",ev:"Cảnh sát tìm thấy dấu vết máu tại hiện trường.",c:"trace back|without a trace|trace evidence",s:"mark|sign|track",a:"",t:"science|law-government|daily-life"},
{w:"track",i:"/træk/",p:"TRAK",pos:"noun,verb",lv:"A2",me:"A path or route; to follow the course of something",mv:"Đường đi; theo dõi",ee:"The runners completed three laps around the track.",ev:"Các vận động viên hoàn thành ba vòng quanh đường chạy.",c:"keep track of|race track|track record",s:"path|trail|route",a:"",t:"sports-fitness|travel|daily-life"},
{w:"tragedy",i:"/ˈtrædʒ.ə.di/",p:"TRAJ-uh-dee",pos:"noun",lv:"B1",me:"An extremely sad event or situation; a serious play with an unhappy ending",mv:"Bi kịch, thảm kịch",ee:"The earthquake was a terrible tragedy for the whole country.",ev:"Trận động đất là một thảm kịch khủng khiếp cho cả đất nước.",c:"personal tragedy|Greek tragedy|tragedy struck",s:"disaster|catastrophe|calamity",a:"comedy|triumph",t:"art-culture|media-entertainment|daily-life"},
{w:"trail",i:"/treɪl/",p:"TRAYL",pos:"noun,verb",lv:"B1",me:"A path through the countryside; to follow behind someone or something",mv:"Đường mòn; theo dấu",ee:"We hiked along a beautiful mountain trail.",ev:"Chúng tôi đi bộ dọc theo một con đường mòn núi tuyệt đẹp.",c:"nature trail|hiking trail|trail behind",s:"path|track|route",a:"",t:"travel|sports-fitness|environment-nature"},
{w:"trap",i:"/træp/",p:"TRAP",pos:"noun,verb",lv:"B1",me:"A device for catching animals; a situation from which it is difficult to escape",mv:"Bẫy; bẫy bắt",ee:"The hunter set a trap to catch the rabbit.",ev:"Người thợ săn đặt bẫy để bắt thỏ.",c:"set a trap|fall into a trap|speed trap",s:"snare|ambush|pitfall",a:"release|freedom",t:"environment-nature|daily-life"},
{w:"treasure",i:"/ˈtrɛʒ.ər/",p:"TREZH-er",pos:"noun,verb",lv:"B1",me:"A quantity of precious objects such as gold or jewels; to value highly",mv:"Kho báu; trân trọng",ee:"The pirates searched for buried treasure on the island.",ev:"Những tên cướp biển tìm kiếm kho báu chôn giấu trên đảo.",c:"treasure hunt|national treasure|treasure chest",s:"riches|wealth|valuables",a:"trash|junk",t:"art-culture|travel|media-entertainment"},
];
fs.writeFileSync(p.join(__dirname,'w63-a2-everyday11.js'),
'module.exports={words:'+JSON.stringify(W)+'};');
console.log('w63-a2-everyday11.js created:',W.length,'words');