const fs=require('fs');const p=require('path');
const W=[
{w:"confound",i:"/kənˈfaʊnd/",p:"kuhn-FOWND",pos:"verb",lv:"C1",me:"to cause surprise or confusion; to prove wrong",mv:"làm bối rối, bác bỏ",ee:"The results confounded the expectations of the researchers.",ev:"Kết quả làm bối rối kỳ vọng của các nhà nghiên cứu.",c:"confound expectations|confound critics|confound the experts|confound predictions",s:"baffle|perplex|bewilder",a:"clarify|confirm|validate",t:"academic-ielts|science|communication"},
{w:"connoisseur",i:"/ˌkɒn.əˈsɜːr/",p:"kon-uh-SUR",pos:"noun",lv:"C1",me:"an expert judge in matters of fine art or taste",mv:"người sành sỏi",ee:"As a wine connoisseur, she could identify the grape variety by taste alone.",ev:"Là người sành rượu, cô ấy có thể nhận biết giống nho chỉ bằng vị.",c:"wine connoisseur|art connoisseur|food connoisseur|connoisseur of",s:"expert|aficionado|specialist",a:"novice|amateur|beginner",t:"food-cooking|art-culture|academic-ielts"},
{w:"consternation",i:"/ˌkɒn.stəˈneɪ.ʃən/",p:"kon-stur-NAY-shuhn",pos:"noun",lv:"C2",me:"feelings of anxiety or dismay at something unexpected",mv:"sự kinh hoàng, hoảng hốt",ee:"The sudden resignation of the CEO caused consternation among shareholders.",ev:"Việc CEO đột ngột từ chức gây hoảng hốt giữa các cổ đông.",c:"cause consternation|to the consternation of|great consternation|consternation among",s:"dismay|alarm|anxiety",a:"calm|composure|relief",t:"emotion-personality|work-business|academic-ielts"},
{w:"consummate",i:"/ˈkɒn.sə.mət/",p:"KON-suh-muht",pos:"adj,verb",lv:"C2",me:"showing great skill and flair; to make complete or perfect",mv:"hoàn hảo, bậc thầy; hoàn thành",ee:"She is a consummate professional who never makes mistakes.",ev:"Cô ấy là chuyên gia bậc thầy không bao giờ mắc lỗi.",c:"consummate professional|consummate skill|consummate performer|consummate ease",s:"supreme|masterful|accomplished",a:"amateur|incompetent|mediocre",t:"work-business|academic-ielts|interview-career"},
{w:"contentious",i:"/kənˈten.ʃəs/",p:"kuhn-TEN-shus",pos:"adj",lv:"C1",me:"causing or likely to cause an argument; controversial",mv:"gây tranh cãi",ee:"The contentious debate over immigration policy divided the nation.",ev:"Cuộc tranh luận gây tranh cãi về chính sách nhập cư chia rẽ quốc gia.",c:"contentious issue|contentious debate|contentious topic|contentious decision",s:"controversial|disputed|divisive",a:"uncontroversial|agreed|harmonious",t:"communication|law-government|academic-ielts"},
{w:"contiguous",i:"/kənˈtɪɡ.ju.əs/",p:"kuhn-TIG-yoo-us",pos:"adj",lv:"C2",me:"sharing a common border; touching; next or together in sequence",mv:"liền kề, tiếp giáp",ee:"The forty-eight contiguous states of the US exclude Alaska and Hawaii.",ev:"Bốn mươi tám bang liền kề của Mỹ không bao gồm Alaska và Hawaii.",c:"contiguous states|contiguous area|contiguous zone|contiguous territory",s:"adjacent|adjoining|neighboring",a:"separate|distant|detached",t:"science|academic-ielts|travel"},
{w:"contrition",i:"/kənˈtrɪʃ.ən/",p:"kuhn-TRISH-uhn",pos:"noun",lv:"C2",me:"the state of feeling remorseful and penitent",mv:"sự hối hận, ăn năn",ee:"He showed genuine contrition for the harm he had caused.",ev:"Anh ấy thể hiện sự hối hận chân thành vì tổn hại đã gây ra.",c:"show contrition|genuine contrition|act of contrition|deep contrition",s:"remorse|repentance|penitence",a:"defiance|pride|indifference",t:"emotion-personality|law-government|academic-ielts"},
{w:"contrivance",i:"/kənˈtraɪ.vəns/",p:"kuhn-TRY-vuhns",pos:"noun",lv:"C2",me:"a device or scheme contrived to serve a particular purpose; an artificial arrangement",mv:"mưu mẹo, thiết bị",ee:"The plot twist felt like a contrivance rather than a natural development.",ev:"Bước ngoặt cốt truyện cảm giác như mưu mẹo hơn là phát triển tự nhiên.",c:"literary contrivance|mechanical contrivance|clever contrivance|contrivance of",s:"device|scheme|invention",a:"naturalness|spontaneity|simplicity",t:"art-culture|academic-ielts|technology"},
{w:"convalescence",i:"/ˌkɒn.vəˈles.əns/",p:"kon-vuh-LES-uhns",pos:"noun",lv:"C1",me:"time spent recovering from an illness or medical treatment",mv:"thời gian hồi phục",ee:"After the surgery, she spent three weeks in convalescence at home.",ev:"Sau phẫu thuật, cô ấy dành ba tuần hồi phục tại nhà.",c:"period of convalescence|during convalescence|convalescence home|long convalescence",s:"recovery|recuperation|rehabilitation",a:"relapse|deterioration|decline",t:"health|academic-ielts|daily-life"},
{w:"convivial",i:"/kənˈvɪv.i.əl/",p:"kuhn-VIV-ee-uhl",pos:"adj",lv:"C2",me:"friendly, lively, and enjoyable",mv:"vui vẻ, thân mật",ee:"The convivial atmosphere at the dinner party made everyone feel at ease.",ev:"Bầu không khí vui vẻ tại bữa tiệc tối khiến mọi người thoải mái.",c:"convivial atmosphere|convivial host|convivial gathering|convivial mood",s:"friendly|jovial|sociable",a:"unfriendly|hostile|gloomy",t:"social-relationships|emotion-personality|academic-ielts"},
{w:"copacetic",i:"/ˌkəʊ.pəˈset.ɪk/",p:"koh-puh-SET-ik",pos:"adj",lv:"C2",me:"in excellent order; very satisfactory",mv:"tốt đẹp, ổn thỏa",ee:"Everything is copacetic — the project is on schedule and under budget.",ev:"Mọi thứ đều tốt đẹp — dự án đúng tiến độ và dưới ngân sách.",c:"everything is copacetic|all copacetic|copacetic situation|copacetic outcome",s:"fine|satisfactory|excellent",a:"problematic|troubled|unsatisfactory",t:"daily-life|work-business|academic-ielts"},
{w:"cornucopia",i:"/ˌkɔː.njəˈkəʊ.pi.ə/",p:"kor-nyuh-KOH-pee-uh",pos:"noun",lv:"C2",me:"an abundant supply of good things; a symbol of plenty",mv:"sự dồi dào, sung túc",ee:"The market offered a cornucopia of fresh fruits and vegetables.",ev:"Chợ cung cấp sự dồi dào trái cây và rau tươi.",c:"cornucopia of|cornucopia of choices|cornucopia of delights|cornucopia of options",s:"abundance|profusion|bounty",a:"scarcity|dearth|shortage",t:"food-cooking|academic-ielts|daily-life"},
{w:"corporeal",i:"/kɔːˈpɔː.ri.əl/",p:"kor-POR-ee-uhl",pos:"adj",lv:"C2",me:"relating to a person's body, especially as opposed to their spirit",mv:"thuộc thể xác, vật chất",ee:"The philosopher distinguished between corporeal and spiritual existence.",ev:"Nhà triết học phân biệt giữa sự tồn tại thể xác và tinh thần.",c:"corporeal form|corporeal punishment|corporeal existence|corporeal being",s:"physical|bodily|material",a:"spiritual|ethereal|immaterial",t:"academic-ielts|health|education"},
{w:"corrigendum",i:"/ˌkɒr.ɪˈdʒen.dəm/",p:"kor-ih-JEN-duhm",pos:"noun",lv:"C2",me:"a thing to be corrected, typically an error in a printed book",mv:"bản đính chính",ee:"The publisher issued a corrigendum for the errors found in the first edition.",ev:"Nhà xuất bản phát hành bản đính chính cho lỗi tìm thấy trong ấn bản đầu.",c:"issue a corrigendum|corrigendum to|corrigendum notice|corrigendum for",s:"correction|erratum|amendment",a:"",t:"education|academic-ielts|communication"},
{w:"coruscate",i:"/ˈkɒr.ə.skeɪt/",p:"KOR-uh-skayt",pos:"verb",lv:"C2",me:"to flash or sparkle; to be brilliantly clever",mv:"lấp lánh, tỏa sáng",ee:"The diamonds coruscated under the bright lights of the exhibition.",ev:"Kim cương lấp lánh dưới ánh đèn sáng của triển lãm.",c:"coruscating wit|coruscating brilliance|coruscating light|coruscating performance",s:"sparkle|glitter|shine",a:"dull|dim|fade",t:"art-culture|academic-ielts|daily-life"}
];
fs.writeFileSync(p.join(__dirname,'w211-final5000.js'),
'module.exports={words:'+JSON.stringify(W)+'};');
console.log('w211-final5000.js created:',W.length,'words');
